import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import FanWarning from "./components/fan-warning";
import Footer from "./components/footer/Footer";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar />
        <div
          className={`bg-ui-dark-purple pt-24`}
        >
          {children}
          <FanWarning />
          <Analytics />
        </div>
        <Footer />
      </body>
    </html>
  );
}
