import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import FanWarning from "./components/fan-warning";
import Footer from "./components/footer/Footer";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Tusker = localFont({
  src: [
    {
      path: "../../public/fonts/TuskerGrotesk-5700Bold.ttf",
      weight: "5700",
      style: "normal",
    },
    {
      path: "../../public/fonts/TuskerGrotesk-6700Bold.ttf",
      weight: "6700",
      style: "normal",
    },
  ],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar />
        <div
          className={`${Tusker.className} font-arial bg-ui-dark-purple pt-24`}
        >
          {children}
          <FanWarning />
          <Analytics />
        </div>
        <Footer />
      </body>
    </html>
  );
}
